/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BalancerListerExpansion allows custom methods to be added to
// BalancerLister.
type BalancerListerExpansion interface{}

// BalancerNamespaceListerExpansion allows custom methods to be added to
// BalancerNamespaceLister.
type BalancerNamespaceListerExpansion interface{}

// BalancerNetworkListerExpansion allows custom methods to be added to
// BalancerNetworkLister.
type BalancerNetworkListerExpansion interface{}

// BalancerNetworkNamespaceListerExpansion allows custom methods to be added to
// BalancerNetworkNamespaceLister.
type BalancerNetworkNamespaceListerExpansion interface{}

// BalancerServiceListerExpansion allows custom methods to be added to
// BalancerServiceLister.
type BalancerServiceListerExpansion interface{}

// BalancerServiceNamespaceListerExpansion allows custom methods to be added to
// BalancerServiceNamespaceLister.
type BalancerServiceNamespaceListerExpansion interface{}

// BalancerTargetListerExpansion allows custom methods to be added to
// BalancerTargetLister.
type BalancerTargetListerExpansion interface{}

// BalancerTargetNamespaceListerExpansion allows custom methods to be added to
// BalancerTargetNamespaceLister.
type BalancerTargetNamespaceListerExpansion interface{}
