/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-hcloud-api/apis/load/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBalancerTargets implements BalancerTargetInterface
type FakeBalancerTargets struct {
	Fake *FakeLoadV1alpha1
	ns   string
}

var balancertargetsResource = schema.GroupVersionResource{Group: "load.hcloud.kubeform.com", Version: "v1alpha1", Resource: "balancertargets"}

var balancertargetsKind = schema.GroupVersionKind{Group: "load.hcloud.kubeform.com", Version: "v1alpha1", Kind: "BalancerTarget"}

// Get takes name of the balancerTarget, and returns the corresponding balancerTarget object, and an error if there is any.
func (c *FakeBalancerTargets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BalancerTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(balancertargetsResource, c.ns, name), &v1alpha1.BalancerTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerTarget), err
}

// List takes label and field selectors, and returns the list of BalancerTargets that match those selectors.
func (c *FakeBalancerTargets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BalancerTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(balancertargetsResource, balancertargetsKind, c.ns, opts), &v1alpha1.BalancerTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BalancerTargetList{ListMeta: obj.(*v1alpha1.BalancerTargetList).ListMeta}
	for _, item := range obj.(*v1alpha1.BalancerTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested balancerTargets.
func (c *FakeBalancerTargets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(balancertargetsResource, c.ns, opts))

}

// Create takes the representation of a balancerTarget and creates it.  Returns the server's representation of the balancerTarget, and an error, if there is any.
func (c *FakeBalancerTargets) Create(ctx context.Context, balancerTarget *v1alpha1.BalancerTarget, opts v1.CreateOptions) (result *v1alpha1.BalancerTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(balancertargetsResource, c.ns, balancerTarget), &v1alpha1.BalancerTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerTarget), err
}

// Update takes the representation of a balancerTarget and updates it. Returns the server's representation of the balancerTarget, and an error, if there is any.
func (c *FakeBalancerTargets) Update(ctx context.Context, balancerTarget *v1alpha1.BalancerTarget, opts v1.UpdateOptions) (result *v1alpha1.BalancerTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(balancertargetsResource, c.ns, balancerTarget), &v1alpha1.BalancerTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerTarget), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBalancerTargets) UpdateStatus(ctx context.Context, balancerTarget *v1alpha1.BalancerTarget, opts v1.UpdateOptions) (*v1alpha1.BalancerTarget, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(balancertargetsResource, "status", c.ns, balancerTarget), &v1alpha1.BalancerTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerTarget), err
}

// Delete takes name of the balancerTarget and deletes it. Returns an error if one occurs.
func (c *FakeBalancerTargets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(balancertargetsResource, c.ns, name), &v1alpha1.BalancerTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBalancerTargets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(balancertargetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BalancerTargetList{})
	return err
}

// Patch applies the patch and returns the patched balancerTarget.
func (c *FakeBalancerTargets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BalancerTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(balancertargetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BalancerTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerTarget), err
}
