/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-hcloud-api/apis/load/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBalancerServices implements BalancerServiceInterface
type FakeBalancerServices struct {
	Fake *FakeLoadV1alpha1
	ns   string
}

var balancerservicesResource = schema.GroupVersionResource{Group: "load.hcloud.kubeform.com", Version: "v1alpha1", Resource: "balancerservices"}

var balancerservicesKind = schema.GroupVersionKind{Group: "load.hcloud.kubeform.com", Version: "v1alpha1", Kind: "BalancerService"}

// Get takes name of the balancerService, and returns the corresponding balancerService object, and an error if there is any.
func (c *FakeBalancerServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BalancerService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(balancerservicesResource, c.ns, name), &v1alpha1.BalancerService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerService), err
}

// List takes label and field selectors, and returns the list of BalancerServices that match those selectors.
func (c *FakeBalancerServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BalancerServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(balancerservicesResource, balancerservicesKind, c.ns, opts), &v1alpha1.BalancerServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BalancerServiceList{ListMeta: obj.(*v1alpha1.BalancerServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BalancerServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested balancerServices.
func (c *FakeBalancerServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(balancerservicesResource, c.ns, opts))

}

// Create takes the representation of a balancerService and creates it.  Returns the server's representation of the balancerService, and an error, if there is any.
func (c *FakeBalancerServices) Create(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.CreateOptions) (result *v1alpha1.BalancerService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(balancerservicesResource, c.ns, balancerService), &v1alpha1.BalancerService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerService), err
}

// Update takes the representation of a balancerService and updates it. Returns the server's representation of the balancerService, and an error, if there is any.
func (c *FakeBalancerServices) Update(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (result *v1alpha1.BalancerService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(balancerservicesResource, c.ns, balancerService), &v1alpha1.BalancerService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBalancerServices) UpdateStatus(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (*v1alpha1.BalancerService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(balancerservicesResource, "status", c.ns, balancerService), &v1alpha1.BalancerService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerService), err
}

// Delete takes name of the balancerService and deletes it. Returns an error if one occurs.
func (c *FakeBalancerServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(balancerservicesResource, c.ns, name), &v1alpha1.BalancerService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBalancerServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(balancerservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BalancerServiceList{})
	return err
}

// Patch applies the patch and returns the patched balancerService.
func (c *FakeBalancerServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BalancerService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(balancerservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BalancerService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BalancerService), err
}
