/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-hcloud-api/apis/load/v1alpha1"
	scheme "kubeform.dev/provider-hcloud-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BalancerServicesGetter has a method to return a BalancerServiceInterface.
// A group's client should implement this interface.
type BalancerServicesGetter interface {
	BalancerServices(namespace string) BalancerServiceInterface
}

// BalancerServiceInterface has methods to work with BalancerService resources.
type BalancerServiceInterface interface {
	Create(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.CreateOptions) (*v1alpha1.BalancerService, error)
	Update(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (*v1alpha1.BalancerService, error)
	UpdateStatus(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (*v1alpha1.BalancerService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BalancerService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BalancerServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BalancerService, err error)
	BalancerServiceExpansion
}

// balancerServices implements BalancerServiceInterface
type balancerServices struct {
	client rest.Interface
	ns     string
}

// newBalancerServices returns a BalancerServices
func newBalancerServices(c *LoadV1alpha1Client, namespace string) *balancerServices {
	return &balancerServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the balancerService, and returns the corresponding balancerService object, and an error if there is any.
func (c *balancerServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BalancerService, err error) {
	result = &v1alpha1.BalancerService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("balancerservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BalancerServices that match those selectors.
func (c *balancerServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BalancerServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BalancerServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("balancerservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested balancerServices.
func (c *balancerServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("balancerservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a balancerService and creates it.  Returns the server's representation of the balancerService, and an error, if there is any.
func (c *balancerServices) Create(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.CreateOptions) (result *v1alpha1.BalancerService, err error) {
	result = &v1alpha1.BalancerService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("balancerservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(balancerService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a balancerService and updates it. Returns the server's representation of the balancerService, and an error, if there is any.
func (c *balancerServices) Update(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (result *v1alpha1.BalancerService, err error) {
	result = &v1alpha1.BalancerService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("balancerservices").
		Name(balancerService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(balancerService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *balancerServices) UpdateStatus(ctx context.Context, balancerService *v1alpha1.BalancerService, opts v1.UpdateOptions) (result *v1alpha1.BalancerService, err error) {
	result = &v1alpha1.BalancerService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("balancerservices").
		Name(balancerService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(balancerService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the balancerService and deletes it. Returns an error if one occurs.
func (c *balancerServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("balancerservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *balancerServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("balancerservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched balancerService.
func (c *balancerServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BalancerService, err error) {
	result = &v1alpha1.BalancerService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("balancerservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
