/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"

	certificatev1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/certificate/v1alpha1"
	firewallv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/firewall/v1alpha1"
	floatingv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/floating/v1alpha1"
	loadv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/load/v1alpha1"
	managedv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/managed/v1alpha1"
	networkv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/network/v1alpha1"
	rdnsv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/rdns/v1alpha1"
	serverv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/server/v1alpha1"
	snapshotv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/snapshot/v1alpha1"
	sshv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/ssh/v1alpha1"
	uploadedv1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/uploaded/v1alpha1"
	volumev1alpha1 "kubeform.dev/provider-hcloud-api/client/clientset/versioned/typed/volume/v1alpha1"

	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	CertificateV1alpha1() certificatev1alpha1.CertificateV1alpha1Interface
	FirewallV1alpha1() firewallv1alpha1.FirewallV1alpha1Interface
	FloatingV1alpha1() floatingv1alpha1.FloatingV1alpha1Interface
	LoadV1alpha1() loadv1alpha1.LoadV1alpha1Interface
	ManagedV1alpha1() managedv1alpha1.ManagedV1alpha1Interface
	NetworkV1alpha1() networkv1alpha1.NetworkV1alpha1Interface
	RdnsV1alpha1() rdnsv1alpha1.RdnsV1alpha1Interface
	ServerV1alpha1() serverv1alpha1.ServerV1alpha1Interface
	SnapshotV1alpha1() snapshotv1alpha1.SnapshotV1alpha1Interface
	SshV1alpha1() sshv1alpha1.SshV1alpha1Interface
	UploadedV1alpha1() uploadedv1alpha1.UploadedV1alpha1Interface
	VolumeV1alpha1() volumev1alpha1.VolumeV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	certificateV1alpha1 *certificatev1alpha1.CertificateV1alpha1Client
	firewallV1alpha1    *firewallv1alpha1.FirewallV1alpha1Client
	floatingV1alpha1    *floatingv1alpha1.FloatingV1alpha1Client
	loadV1alpha1        *loadv1alpha1.LoadV1alpha1Client
	managedV1alpha1     *managedv1alpha1.ManagedV1alpha1Client
	networkV1alpha1     *networkv1alpha1.NetworkV1alpha1Client
	rdnsV1alpha1        *rdnsv1alpha1.RdnsV1alpha1Client
	serverV1alpha1      *serverv1alpha1.ServerV1alpha1Client
	snapshotV1alpha1    *snapshotv1alpha1.SnapshotV1alpha1Client
	sshV1alpha1         *sshv1alpha1.SshV1alpha1Client
	uploadedV1alpha1    *uploadedv1alpha1.UploadedV1alpha1Client
	volumeV1alpha1      *volumev1alpha1.VolumeV1alpha1Client
}

// CertificateV1alpha1 retrieves the CertificateV1alpha1Client
func (c *Clientset) CertificateV1alpha1() certificatev1alpha1.CertificateV1alpha1Interface {
	return c.certificateV1alpha1
}

// FirewallV1alpha1 retrieves the FirewallV1alpha1Client
func (c *Clientset) FirewallV1alpha1() firewallv1alpha1.FirewallV1alpha1Interface {
	return c.firewallV1alpha1
}

// FloatingV1alpha1 retrieves the FloatingV1alpha1Client
func (c *Clientset) FloatingV1alpha1() floatingv1alpha1.FloatingV1alpha1Interface {
	return c.floatingV1alpha1
}

// LoadV1alpha1 retrieves the LoadV1alpha1Client
func (c *Clientset) LoadV1alpha1() loadv1alpha1.LoadV1alpha1Interface {
	return c.loadV1alpha1
}

// ManagedV1alpha1 retrieves the ManagedV1alpha1Client
func (c *Clientset) ManagedV1alpha1() managedv1alpha1.ManagedV1alpha1Interface {
	return c.managedV1alpha1
}

// NetworkV1alpha1 retrieves the NetworkV1alpha1Client
func (c *Clientset) NetworkV1alpha1() networkv1alpha1.NetworkV1alpha1Interface {
	return c.networkV1alpha1
}

// RdnsV1alpha1 retrieves the RdnsV1alpha1Client
func (c *Clientset) RdnsV1alpha1() rdnsv1alpha1.RdnsV1alpha1Interface {
	return c.rdnsV1alpha1
}

// ServerV1alpha1 retrieves the ServerV1alpha1Client
func (c *Clientset) ServerV1alpha1() serverv1alpha1.ServerV1alpha1Interface {
	return c.serverV1alpha1
}

// SnapshotV1alpha1 retrieves the SnapshotV1alpha1Client
func (c *Clientset) SnapshotV1alpha1() snapshotv1alpha1.SnapshotV1alpha1Interface {
	return c.snapshotV1alpha1
}

// SshV1alpha1 retrieves the SshV1alpha1Client
func (c *Clientset) SshV1alpha1() sshv1alpha1.SshV1alpha1Interface {
	return c.sshV1alpha1
}

// UploadedV1alpha1 retrieves the UploadedV1alpha1Client
func (c *Clientset) UploadedV1alpha1() uploadedv1alpha1.UploadedV1alpha1Interface {
	return c.uploadedV1alpha1
}

// VolumeV1alpha1 retrieves the VolumeV1alpha1Client
func (c *Clientset) VolumeV1alpha1() volumev1alpha1.VolumeV1alpha1Interface {
	return c.volumeV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.certificateV1alpha1, err = certificatev1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.firewallV1alpha1, err = firewallv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.floatingV1alpha1, err = floatingv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.loadV1alpha1, err = loadv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.managedV1alpha1, err = managedv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.networkV1alpha1, err = networkv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.rdnsV1alpha1, err = rdnsv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.serverV1alpha1, err = serverv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.snapshotV1alpha1, err = snapshotv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.sshV1alpha1, err = sshv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.uploadedV1alpha1, err = uploadedv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.volumeV1alpha1, err = volumev1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.certificateV1alpha1 = certificatev1alpha1.NewForConfigOrDie(c)
	cs.firewallV1alpha1 = firewallv1alpha1.NewForConfigOrDie(c)
	cs.floatingV1alpha1 = floatingv1alpha1.NewForConfigOrDie(c)
	cs.loadV1alpha1 = loadv1alpha1.NewForConfigOrDie(c)
	cs.managedV1alpha1 = managedv1alpha1.NewForConfigOrDie(c)
	cs.networkV1alpha1 = networkv1alpha1.NewForConfigOrDie(c)
	cs.rdnsV1alpha1 = rdnsv1alpha1.NewForConfigOrDie(c)
	cs.serverV1alpha1 = serverv1alpha1.NewForConfigOrDie(c)
	cs.snapshotV1alpha1 = snapshotv1alpha1.NewForConfigOrDie(c)
	cs.sshV1alpha1 = sshv1alpha1.NewForConfigOrDie(c)
	cs.uploadedV1alpha1 = uploadedv1alpha1.NewForConfigOrDie(c)
	cs.volumeV1alpha1 = volumev1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.certificateV1alpha1 = certificatev1alpha1.New(c)
	cs.firewallV1alpha1 = firewallv1alpha1.New(c)
	cs.floatingV1alpha1 = floatingv1alpha1.New(c)
	cs.loadV1alpha1 = loadv1alpha1.New(c)
	cs.managedV1alpha1 = managedv1alpha1.New(c)
	cs.networkV1alpha1 = networkv1alpha1.New(c)
	cs.rdnsV1alpha1 = rdnsv1alpha1.New(c)
	cs.serverV1alpha1 = serverv1alpha1.New(c)
	cs.snapshotV1alpha1 = snapshotv1alpha1.New(c)
	cs.sshV1alpha1 = sshv1alpha1.New(c)
	cs.uploadedV1alpha1 = uploadedv1alpha1.New(c)
	cs.volumeV1alpha1 = volumev1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
